version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ads
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "5433:5432"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ads
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - localhost